<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 12 July 2025 3:52:50</msg><msg code="0" type="0">Classifying points...</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\ClassifyPointsOnly.py", line 58, in &lt;module&gt;
﻿    classify_points(levelling_segments_input, source_points_input, points_classification_output, print_messages = True)
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 689, in classify_points
﻿    editor = start_editing(ws)
﻿             ^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Helpers.py", line 76, in start_editing
﻿    editor: Editor = Editor(workspace=workspace, multiuser_mode=True)
﻿                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿RuntimeError: cannot open workspace
</msg><msg code="0" type="0">Failed script Classify Points Only...</msg><msg code="-2147467259" type="100">Failed to execute (ClassifyPointsOnly).</msg><msg code="0" type="3">Failed at Saturday, 12 July 2025 3:52:59 (Elapsed Time: 9.71 seconds)</msg></messages>