<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 15 February 2025 23:28:57</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\Data Update\CalculateGravimetricCorrections.py", line 16, in &lt;module&gt;
﻿    calculate_gravimetric_corrections(lines_fc, points_fc)
﻿  File "E:\git\LevellingThesis\Code\Utils\Gravimetry.py", line 33, in calculate_gravimetric_corrections
﻿    editor = start_editing(wc)
﻿             ^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Helpers.py", line 69, in start_editing
﻿    editor: Editor = Editor(workspace=workspace, multiuser_mode=True)
﻿                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿RuntimeError: cannot open workspace
</msg><msg code="0" type="0">Failed script Calculate Gravimetric Correction...</msg><msg code="-2147467259" type="100">Failed to execute (CalculateGravCorrection).</msg><msg code="0" type="3">Failed at Saturday, 15 February 2025 23:29:01 (Elapsed Time: 4.22 seconds)</msg></messages>