<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 5 July 2025 23:16:14</msg><msg code="0" type="0">Starting the generalization process...</msg><msg code="0" type="0">Generalizing sorted segments...</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\GeneralizationOfAlreadySortedSegments.py", line 84, in &lt;module&gt;
﻿    generalize_segments(sorted_segments, generalized_lines_output)
﻿  File "E:\git\LevellingThesis\Code\GeneralizationOfAlreadySortedSegments.py", line 32, in generalize_segments
﻿    generalized_lines = generalize_sorted_segments(sorted_segments, generalized_lines_output, print_messages=True)
﻿                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 980, in generalize_sorted_segments
﻿    fill_midpoints_and_precise_levelling_source_summary(generalized_lines, sorted_dissolved_lines)
﻿  File "E:\git\LevellingThesis\Code\Utils\Generalization.py", line 139, in fill_midpoints_and_precise_levelling_source_summary
﻿    point_names = get_point_names(point_codes)
﻿                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Points.py", line 28, in get_point_names
﻿    for row in cursor:
﻿RuntimeError: Cannot find field 'FullName'
</msg><msg code="0" type="0">Failed script Generalization Of Already Sorted Data...</msg><msg code="-2147467259" type="100">Failed to execute (GeneralizationOfAlreadySortedData).</msg><msg code="0" type="3">Failed at Saturday, 5 July 2025 23:16:39 (Elapsed Time: 24.62 seconds)</msg></messages>