<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, 18 January 2025 23:35:03</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\FindLoops.py", line 172, in &lt;module&gt;
﻿    find_loops(levelling_lines_input, source_points_input, loops_type, loops_output)
﻿  File "E:\git\LevellingThesis\Code\FindLoops.py", line 36, in find_loops
﻿    create_polygons_from_loops(polygons_data,loops_output,sr)
﻿  File "E:\git\LevellingThesis\Code\Utils\Loops.py", line 117, in create_polygons_from_loops
﻿    out_folder, fc_name = os.path.split(out_fc)
﻿                          ^^
﻿NameError: name 'os' is not defined
</msg><msg code="0" type="0">Failed script Find Loops...</msg><msg code="-2147467259" type="100">Failed to execute (FindLoops).</msg><msg code="0" type="3">Failed at Saturday, 18 January 2025 23:35:04 (Elapsed Time: 0.93 seconds)</msg></messages>