<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Monday, 7 July 2025 23:31:37</msg><msg code="-2147467259" type="100">﻿Traceback (most recent call last):
﻿  File "E:\git\LevellingThesis\Code\Data Update\AddGeographicCoordinates.py", line 14, in &lt;module&gt;
﻿    calculate_geographic_coordinates(points_fc)
﻿  File "E:\git\LevellingThesis\Code\Utils\Points.py", line 86, in calculate_geographic_coordinates
﻿    editor = start_editing(wc)
﻿             ^^^^^^^^^^^^^^^^^
﻿  File "E:\git\LevellingThesis\Code\Utils\Helpers.py", line 76, in start_editing
﻿    editor: Editor = Editor(workspace=workspace, multiuser_mode=True)
﻿                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿RuntimeError: cannot open workspace
</msg><msg code="0" type="0">Failed script Add Geographic Coordinates...</msg><msg code="-2147467259" type="100">Failed to execute (AddGeographicCoordinates).</msg><msg code="0" type="3">Failed at Monday, 7 July 2025 23:31:48 (Elapsed Time: 10.88 seconds)</msg></messages>